### ISSUE TITLE
Getting an error with wabbajack installation.

### ISSUE THREAD

**Issue by taskinberkay** [Oghma-Infinium/Fahluaan#3]
**Describe the bug**
Installation fails with error message.

**Crash Logs**
03:30:24.681 [INFO] (Wabbajack.Installer.StandardInstaller) Verifying mods\Fahluaan - NPC Merge\NPC Appearances Merged0.bsa
03:30:24.862 [ERROR] (Wabbajack.Installer.StandardInstaller) Hashes for BSA don't match after extraction, mods\Fahluaan - NPC Merge\NPC Appearances Merged0.bsa, TEMP_BSA_FILES\735f4d6b-2649-454d-bab8-88895871aa73\meshes\actors\character\facegendata\facegeom\skyrim.esm\000a2c8c.nif, 2qVGgW/UyPs=, f6yL4UTXruE=
03:30:25.315 [ERROR] (Wabbajack.InstallerVM) Hashes for mods\Fahluaan - NPC Merge\NPC Appearances Merged0.bsa file TEMP_BSA_FILES\735f4d6b-2649-454d-bab8-88895871aa73\meshes\actors\character\facegendata\facegeom\skyrim.esm\000a2c8c.nif did not match, expected 2qVGgW/UyPs= got f6yL4UTXruE=|System.Exception: Hashes for mods\Fahluaan - NPC Merge\NPC Appearances Merged0.bsa file TEMP_BSA_FILES\735f4d6b-2649-454d-bab8-88895871aa73\meshes\actors\character\facegendata\facegeom\skyrim.esm\000a2c8c.nif did not match, expected 2qVGgW/UyPs= got f6yL4UTXruE=
   at Wabbajack.Installer.AInstaller`1.ThrowOnNonMatchingHash(CreateBSA bsa, Directive directive, AFile state, Hash hash) in C:\oss\wabbajack\Wabbajack.Installer\AInstaller.cs:line 311
   at Wabbajack.Installer.StandardInstaller.<>c__DisplayClass8_1.<<BuildBSAs>b__3>d.MoveNext() in C:\oss\wabbajack\Wabbajack.Installer\StandardInstaller.cs:line 375
--- End of stack trace from previous location ---
   at Wabbajack.Installer.StandardInstaller.<>c__DisplayClass8_1.<<BuildBSAs>b__3>d.MoveNext() in C:\oss\wabbajack\Wabbajack.Installer\StandardInstaller.cs:line 376
--- End of stack trace from previous location ---
   at Wabbajack.Common.AsyncParallelExtensions.<>c__DisplayClass5_1`3.<<PMapAllBatchedAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Wabbajack.Common.AsyncParallelExtensions.PMapAllBatchedAsync[TIn,TJob,TOut](IEnumerable`1 coll, IResource`1 limiter, Func`2 mapFn)+MoveNext()
   at Wabbajack.Common.AsyncParallelExtensions.PMapAllBatchedAsync[TIn,TJob,TOut](IEnumerable`1 coll, IResource`1 limiter, Func`2 mapFn)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Wabbajack.Common.AsyncParallelExtensions.ToHashSet[T](IAsyncEnumerable`1 coll, Predicate`1 filter) in C:\oss\wabbajack\Wabbajack.Common\AsyncParallelExtensions.cs:line 235
   at Wabbajack.Common.AsyncParallelExtensions.ToHashSet[T](IAsyncEnumerable`1 coll, Predicate`1 filter) in C:\oss\wabbajack\Wabbajack.Common\AsyncParallelExtensions.cs:line 235
   at Wabbajack.Installer.StandardInstaller.BuildBSAs(CancellationToken token) in C:\oss\wabbajack\Wabbajack.Installer\StandardInstaller.cs:line 365
   at Wabbajack.Installer.StandardInstaller.BuildBSAs(CancellationToken token) in C:\oss\wabbajack\Wabbajack.Installer\StandardInstaller.cs:line 365
   at Wabbajack.Installer.StandardInstaller.Begin(CancellationToken token) in C:\oss\wabbajack\Wabbajack.Installer\StandardInstaller.cs:line 149
   at Wabbajack.InstallerVM.<BeginInstall>b__126_0() in C:\oss\wabbajack\Wabbajack.App.Wpf\View Models\Installers\InstallerVM.cs:line 483
03:51:56.740 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Ascalon
03:51:56.740 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Ascalon

**Technical (please complete the following information):**
 - OS: [e.g. Windows 10]
 - CPU: Ryzen 5700X
 - GPU: AMD Radeon 6800XT
 - RAM: 64 GB
 - Type of Drive: NVME/M.2
 - Pagefile Size: 40960
 - List Version: 1.2.4

**Comment by aljoxo** [comment]
Please upload your `wabbajack.current.log` file after your failure to install.

What you copy pasted from the log is insufficient information.

**Comment by taskinberkay** [comment]
Here you go.
[Wabbajack.current.log](https://github.com/Oghma-Infinium/Fahluaan/files/12409448/Wabbajack.current.log)

**Comment by aljoxo** [comment]
look for this file if it exists on your PC and delete it `NPC Appearances Merged0.bsa`

**Comment by taskinberkay** [comment]
Thanks for the help it worked.
